extern NSString *const SCSPlayingCardDidBecomeFaceUpNotification;
extern NSString *const SCSMatchMeGameDidIdentifyMatchingCardsNotification;
extern NSString *const SCSMatchMeGameDidIdentifyNonmatchingCardsNotification;

