#import "SCSConstants.h"

NSString *const SCSPlayingCardDidBecomeFaceUpNotification = @"SCSPlayingCardDidBecomeFaceUpNotification";
NSString *const SCSPlayingCardCellDidFinishFlippingCardNotification = @"SCSPlayingCardCellDidFinishFlippingCardNotification";
NSString *const SCSMatchMeGameDidIdentifyMatchingCardsNotification = @"SCSMatchMeGameDidIdentifyMatchingCardsNotification";
NSString *const SCSMatchMeGameDidIdentifyNonmatchingCardsNotification = @"SCSMatchMeGameDidIdentifyNonmatchingCardsNotification";